# Generated by Django 5.1.2 on 2024-12-09 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_message_log_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('mensagem', models.TextField(max_length=500)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 11, 23, 44, 305892)),
        ),
    ]
