# Generated by Django 5.1.2 on 2024-12-09 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_message_log_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={},
        ),
        migrations.AlterField(
            model_name='message',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 11, 41, 10, 410983)),
        ),
    ]
